# Install modules by Homebrew.
#
# $ brew tap Homebrew/bundle
# $ brew bundle

tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "carthage"
brew "cowsay"
brew "ctags"
brew "curl", args: ["with-nghttp2"], link: true
brew "direnv"
brew "fortune"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "graphviz"
brew "heroku"
brew "imagemagick"
brew "jq"
brew "peco"
brew "reattach-to-user-namespace"
brew "rbenv"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "vim"
brew "yarn"
cask "android-studio"
cask "atom"
cask "cheatsheet"
cask "clipy"
cask "coteditor"
cask "docker"
cask "dropbox"
cask "evernote"
cask "flux"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "insomnia"
cask "intellij-idea"
cask "kindle"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklookapk"
cask "quicklook-csv"
cask "quicklook-json"
cask "quip"
cask "slack"
cask "sublime-text"
cask "vagrant"
cask "virtualbox"

