# Install modules by Homebrew.
#
# $ brew tap Homebrew/bundle
# $ brew bundle
#
#
# If failed to install virtualbox,
# check [System Preferences] > [Security & Privacy] > [General],
# and run the command below:
#
# $ brew cask reinstall --force virtualbox
#
# See [Cannot install virtualbox on macOS High Sierra](https://github.com/caskroom/homebrew-cask/issues/39369).

tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
#brew "ansible"
brew "anyenv"
brew "awscli"
#brew "bundletool"
#brew "carthage"
#brew "cookiecutter"
brew "cowsay"
#brew "ctags"
brew "curl"
brew "direnv"
#brew "exiftool"
#brew "ffmpeg"
brew "fortune"
brew "gh"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "gnupg"
brew "graphviz"
#brew "gstreamer"
#brew "gst-plugins-base"
#brew "gst-plugins-good"
#brew "gst-plugins-bad"
#brew "gst-plugins-ugly"
#brew "gst-rtsp-server"
#brew "heroku"
brew "htop"
#brew "imagemagick"
#brew "inetutils"
brew "jq"
brew "mas"
brew "mysql"
brew "nmap"
#brew "opencv"
brew "openssl"
#brew "peco"
#brew "postgresql"
brew "pstree"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "vim"
brew "wget"
#brew "yarn"
#brew "zsh-autosuggestions"
#cask "alfred"
#cask "amazon-music"
#cask "amazon-workspaces"
#cask "android-file-transfer"
cask "android-studio"
#cask "anydesk"
cask "atom"
cask "charles"
#cask "cheatsheet"
cask "clipy"
#cask "coteditor"
#cask "cursor"
#cask "cyberduck"
#cask "dash"
#cask "dbeaver-community"
#cask "deepl"
#cask "discord"
cask "docker"
cask "dropbox"
#cask "epic-games"
cask "evernote"
#cask "figma"
#cask "fing"
#cask "firefox"
cask "flux"
#cask "franz"
#cask "fritzing"
#cask "gather"
#cask "gimp"
#cask "google-backup-and-sync"
cask "google-chrome"
#cask "google-chrome-beta"
#cask "google-chrome-canary"
#cask "google-chrome-dev"
#cask "google-cloud-sdk"
cask "google-japanese-ime"
#cask "inkscape"
#cask "insomnia"
#cask "intellij-idea"
#cask "iterm2"
#cask "kindle"
#cask "macs-fan-control"
#cask "mcreator"
#cask "microsoft-edge"
#cask "microsoft-teams"
#cask "mysqlworkbench"
#cask "notion"
#cask "obs"
#cask "obs-virtualcam"
#cask "powershell"
#cask "phpstorm"
#cask "qgis"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklookapk"
cask "quicklook-csv"
cask "quicklook-json"
#cask "quip"
#cask "raycast"
#cask "sequel-pro"
#cask "sketch"
#cask "skitch"
cask "slack"
#cask "soundflower"
#cask "spotify"
#cask "steam"
cask "sublime-text"
#cask "tableplus"
#cask "teamviewer"
#cask "timemachineeditor"
#cask "unity"
#cask "unity-hub"
#cask "vagrant"
#cask "virtualbox"
cask "visual-studio-code"
#cask "vlc"
#cask "warp"
#cask "whatsapp"
#cask "zoom"
#mas "Fusion 360", id: 868968810
mas "LINE", id: 539883307
#mas "Memory Clean 2", id: 1114591412
#mas "Microsoft Remote Desktop", id: 1295203466
#mas "LadioCast", id: 411213048
mas "Xcode", id: 497799835

